server:
  port: 8888

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password:
      lettuce:
        pool:
          min-idle: 10
          max-idle: 20
          max-active: 50

nql:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSid: 2c94811c9860a9c4019917c161c81e5a
      accountToken: b9f8befa634a4557a396eb4d9fc541f5
      appId: 2c94811c9860a9c4019917c1632f1e61
      templateId: 1